# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0623d770213707ccbcedfa24f4642383980ffcae2d4354ff0b2a74a4f90041eff16b73c2b9f1e8af722ca23ea203e705f2aa89d24ea855044717423301479119

test:
  secret_key_base: 47474b2a7770106b0b5f0450fc50f581878e161b42e3bf97465b9daef6bfb6a3897e37f1ad98574f89b98a010d24fcc384fbad3c399e2d594c157bbc93c494ec

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
